languageCode = "en-us"
title = "Don't Panic"
baseURL = "https://commaok.xyz/"
theme = "hugo-cactus-theme"
publishDir = "docs"
rssLimit = 10

[taxonomies]
    category = "categories" 
    tag = "tags"

[outputs]
    home = ["HTML", "RSS"]
    page = ["HTML"]
    taxonomy = ["HTML", "RSS"]
    term = ["HTML", "RSS"]

[params]
	name = "Josh Bleecher Snyder"
	description = "Words about Go and software"
	bio = "Gopher, parent, fruit trees"
	enableRSS = true

	# Navigation links
	home = ""
	#about = ""
	subscribe = "RSS"
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = ""
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = "It's me."
	tweet = ""
	share = ""
	# 404 page
	title404 = ""
	subtitle404 = ""
	customCSS = ["css/copy-code.css"]
	customJS = ["js/copy-code.js"]

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"

[social]
    github   = "https://www.github.com/josharian"
